# Generated by Django 4.2.2 on 2023-07-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_livro_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='data_lancamento',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='numero_paginas',
        ),
    ]
