# Generated by Django 3.2.12 on 2023-07-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_livro_data_lancamento_remove_livro_formato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='capa',
        ),
    ]
